### PR TITLE
Update to Akka 2.4

### PR DESCRIPTION
**Pull request by johanandren**
Upgrade to akka 2.4.0-RC1 (and Scala 2.11.7 and sbt 0.13.8) right now, do not merge yet!

### CODE REVIEW

**Comment by patriknw** [comment]
LGTM

**Comment by ktoso** [comment]
LGTM, do we want to merge these or keep alive until 2.4 final is out and then update/merge?

**Comment by patriknw** [comment]
We normally only publish these for final versions. It might be close enough now, but let's wait until final.

**Comment by patriknw** [comment]
I fixed doc links also, in https://github.com/typesafehub/activator-akka-clustering/pull/11

**Comment by johanandren** [comment]
That's why I did it so fast, I didn't do it all... :P

Sorry about that.

**Comment by patriknw** [comment]
no problem

**Pull request closed without merging**
